import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import*as XLSX from'xlsx';import'./style.css';import{supabase}from'./supabase';
const members=['ליאת','אורן','רום','נועם','אלון','אמיר','ג׳וי'];
type Tx={date:string,description:string,amount:number,type:string,category:string,reference:string,includedInExpenses:boolean,yyyymm?:string,sourceType?:string,subcategory?:string,nature?:string,ordinal?:number};
type DbTx={id:string,transaction_date:string,description:string,amount:number,transaction_type:string,category:string|null,subcategory:string|null,included_in_expenses:boolean,source_type:string,yyyymm:number|null,expense_nature:string|null};
type Mapping={source_type:string,match_text:string,category:string,subcategory:string|null,included_in_expenses:boolean};
const months=[['','הכל'],['202603','מרץ'],['202604','אפריל'],['202605','מאי'],['202606','יוני'],['202607','יולי'],['202608','אוגוסט']];
function money(n:number){return new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS'}).format(n)}
function isCardSettlement(d:string){return /ישראכרט|מקס\s*הבינלאומי|כרטיסי\s*אשראי\s*לי/i.test(d||'')}
function isInvestmentOrTransfer(d:string){return /פק\s*קרן|פיקדון|רכישת\s*מט["״]?ח|המרת\s*מט["״]?ח|העברה\s+מהחשבון|העברה\s+לחשבון|העברה\s+בין/i.test(d||'')}
function guessCategory(s:string){if(isCardSettlement(s))return'כרטיסי אשראי';if(/משכורת/.test(s))return'משכורת';if(/קצבת\s*ילדים/.test(s))return'קצבת ילדים';if(/משכנת/.test(s))return'דיור ושירותים';if(/ראלי|ריאלי/.test(s))return'חינוך';if(/מכבי|רמב|איזנבוד|אופטיקנה/.test(s))return'בריאות';if(/סלקום אנרג/.test(s))return'דיור ושירותים';if(/פלאפון|בזק/.test(s))return'תקשורת';if(/שופרסל|רמי לוי|סטופמרקט|AM:PM|PM:AM/.test(s))return'מזון';if(/ארקיע|אל-על|אל על|איסתא|מלון/.test(s))return'נופש ונסיעות';if(/YELLOW|סונול|פז /.test(s))return'רכב ותחבורה';if(/מסעד|קפה|מחניודה|פסטורי/.test(s))return'מסעדות';return'לא מסווג'}
function asNumber(v:any){return typeof v==='number'?v:Number(String(v??'').replace(/[₪,\s]/g,''))||0}
function iso(v:any){if(v instanceof Date)return v.toISOString().slice(0,10);const s=String(v??'').trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:new Date(s).toISOString().slice(0,10)}
function hash(r:Tx,file:string){const raw=[file,r.ordinal??'',iso(r.date),r.description,r.amount.toFixed(2),r.reference].join('|');let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}return'v3_'+(h>>>0).toString(16)+'_'+raw.length}
function billingMonth(name:string){const n=name.match(/1788122731881|1788122470543|1788122456822|1788122208047|1788121906677|1788119346635/)?.[0];return({'1788122731881':'202603','1788122470543':'202604','1788122456822':'202605','1788122208047':'202606','1788121906677':'202607','1788119346635':'202608'}as any)[n||'']||''}
function applyMapping(r:Tx,maps:Mapping[]){const d=r.description.toLocaleLowerCase('he-IL');const matches=maps.filter(m=>(!m.source_type||m.source_type===r.sourceType)&&d.includes((m.match_text||'').toLocaleLowerCase('he-IL'))).sort((a,b)=>(b.match_text||'').length-(a.match_text||'').length);const m=matches[0];return m?{...r,category:m.category||r.category,subcategory:m.subcategory||undefined,includedInExpenses:m.included_in_expenses}:r}
function parseCard(raw:any[][],file:string,startOrdinal=0){const out:Tx[]=[];let h:string[]|null=null;let ordinal=startOrdinal;for(const row of raw){const c=row.map(v=>String(v??'').trim());if(c.includes('תאריך עסקה')&&c.some(v=>/שם\s*העסק/.test(v))&&c.some(v=>/^סכום חיוב$/.test(v))){h=c;continue}if(!h)continue;const idx=(re:RegExp)=>h!.findIndex(v=>re.test(v)),di=idx(/^תאריך עסקה$/),mi=idx(/שם\s*העסק/),ci=idx(/^סכום חיוב$/),ri=idx(/פירוט/);if(di<0||mi<0||ci<0)continue;const desc=String(row[mi]??'').trim(),charge=asNumber(row[ci]);if(!desc||!row[di]||charge===0||/סה"?כ/.test(desc))continue;const amount=-charge;out.push({date:iso(row[di]),description:desc,amount,type:amount<0?'expense':'refund',category:guessCategory(desc),reference:ri>=0?String(row[ri]??''):'',includedInExpenses:true,yyyymm:billingMonth(file),sourceType:'credit_card',nature:'variable',ordinal:ordinal++})}return out}
function App(){const[user,setUser]=useState<any>(),[email,setEmail]=useState('orentanhum@gmail.com'),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[page,setPage]=useState('home'),[db,setDb]=useState<DbTx[]>([]),[month,setMonth]=useState(''),[sourceFilter,setSourceFilter]=useState(''),[search,setSearch]=useState(''),[preview,setPreview]=useState<Tx[]>([]),[fileName,setFileName]=useState(''),[saving,setSaving]=useState(false);const input=useRef<HTMLInputElement>(null);
useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{data:s}=supabase.auth.onAuthStateChange((_e,x)=>setUser(x?.user||null));return()=>s.subscription.unsubscribe()},[]);useEffect(()=>{if(user)load()},[user]);
async function familyId(){const{data,error}=await supabase.from('family_members').select('family_id').eq('user_id',user.id).eq('is_active',true).limit(1).maybeSingle();if(error||!data)throw new Error('לא נמצאה משפחה פעילה');return data.family_id}
async function load(){try{const fid=await familyId();const{data,error}=await supabase.from('transactions').select('id,transaction_date,description,amount,transaction_type,category,subcategory,included_in_expenses,source_type,yyyymm,expense_nature').eq('family_id',fid).eq('is_active',true).order('transaction_date',{ascending:false}).limit(5000);if(error)throw error;setDb((data||[])as DbTx[])}catch(e:any){setMsg(e.message)}}
async function login(e:React.FormEvent){e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}
async function getMappings(fid:string){const{data,error}=await supabase.from('transaction_mappings').select('source_type,match_text,category,subcategory,included_in_expenses').eq('family_id',fid).eq('is_active',true).eq('is_approved',true);if(error)throw error;return(data||[])as Mapping[]}
async function importFile(file:File){try{setFileName(file.name);const fid=await familyId(),maps=await getMappings(fid);const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});let card:Tx[]=[];let ordinal=0;for(const sn of wb.SheetNames){const raw:any[][]=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:true});const hi=raw.findIndex(r=>r.some(v=>String(v).trim()==='תיאור')&&r.some(v=>String(v).trim()==='חובה'));if(hi>=0){const h=raw[hi].map(v=>String(v).trim()),ix=(n:string)=>h.indexOf(n);const out=raw.slice(hi+1).filter(r=>r[ix('תיאור')]&&(r[ix('חובה')]||r[ix('זכות')])).map((r,i)=>{const debit=Math.abs(asNumber(r[ix('חובה')])),credit=Math.abs(asNumber(r[ix('זכות')])),d=String(r[ix('תיאור')]),special=isCardSettlement(d)||isInvestmentOrTransfer(d),amount=debit?-debit:credit;return{date:iso(r[ix('תאריך')]),description:d,amount,type:special?'transfer':debit?'expense':'income',category:isCardSettlement(d)?'כרטיסי אשראי':guessCategory(d),reference:String(r[ix('אסמכתא')]||''),includedInExpenses:!special,yyyymm:iso(r[ix('תאריך')]).slice(0,7).replace('-',''),sourceType:'bank',nature:special?'one_time':'variable',ordinal:ordinal+i}as Tx});setPreview(out.map(r=>applyMapping(r,maps)));setMsg(`נמצאו ${out.length} תנועות בבנק`);return}const part=parseCard(raw,file.name,ordinal);ordinal+=part.length;card.push(...part)}card=card.map(r=>applyMapping(r,maps));setPreview(card);const net=card.reduce((s,r)=>s+r.amount,0);setMsg(`נמצאו ${card.length} תנועות | נטו ${money(Math.abs(net))}`)}catch(e:any){setMsg('שגיאה בניתוח הקובץ: '+e.message)}}
async function save(){if(!preview.length)return;setSaving(true);try{const fid=await familyId();let saved=0;for(let i=0;i<preview.length;i+=100){const batch=preview.slice(i,i+100).map(r=>({family_id:fid,member_id:null,transaction_date:r.date,description:r.description,amount:r.amount,currency:'ILS',transaction_type:r.type,category:r.category,subcategory:r.subcategory||null,included_in_expenses:r.includedInExpenses,reference:r.reference||null,source_type:r.sourceType,source_file:fileName,yyyymm:Number(r.yyyymm),status:'done',is_active:true,expense_nature:r.nature||null,is_core_living_expense:r.includedInExpenses,created_by:user.id,updated_by:user.id,fingerprint:hash(r,fileName)}));const{data,error}=await supabase.from('transactions').upsert(batch,{onConflict:'family_id,fingerprint',ignoreDuplicates:true}).select('id');if(error)throw error;saved+=data?.length||0}setMsg(`נשמרו ${saved} תנועות`);setPreview([]);await load()}catch(e:any){setMsg('שגיאה: '+e.message)}finally{setSaving(false)}}
if(user===undefined)return null;if(!user)return <div dir="rtl" className="authPage"><form className="authCard" onSubmit={login}><h1>FamilyApp</h1><h2>כניסה</h2><input value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>כניסה</button>{msg&&<p>{msg}</p>}</form></div>;
const filtered=db.filter(r=>(!month||String(r.yyyymm)===month)&&(!sourceFilter||r.source_type===sourceFilter)&&(!search||r.description.includes(search)||r.category?.includes(search))),expenses=-filtered.filter(r=>r.amount<0&&r.included_in_expenses&&r.transaction_type==='expense').reduce((s,r)=>s+r.amount,0),income=filtered.filter(r=>r.amount>0&&r.transaction_type==='income').reduce((s,r)=>s+r.amount,0),refunds=filtered.filter(r=>r.amount>0&&r.transaction_type==='refund').reduce((s,r)=>s+r.amount,0);const cats=Object.entries(filtered.filter(r=>r.amount<0&&r.included_in_expenses).reduce((a:any,r)=>{a[r.category||'לא מסווג']=(a[r.category||'לא מסווג']||0)+Math.abs(r.amount);return a},{})).sort((a:any,b:any)=>b[1]-a[1]);
const filters=<div className="actions"><select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m[0]} value={m[0]}>{m[1]}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">כל המקורות</option><option value="bank">בנק</option><option value="credit_card">אשראי</option></select><input placeholder="חיפוש..." value={search} onChange={e=>setSearch(e.target.value)}/></div>;
return <div dir="rtl"><header><div><h1>FamilyApp</h1><span>משפחת תנחום</span></div><nav><button onClick={()=>setPage('home')}>דף הבית</button><button onClick={()=>setPage('members')}>בני משפחה</button><button onClick={()=>setPage('transactions')}>תנועות כספיות</button><button onClick={()=>setPage('summary')}>סיכומים</button><button className="secondary" onClick={()=>supabase.auth.signOut()}>יציאה</button></nav></header><main>{page==='home'&&<><h2>שלום משפחת תנחום 👋</h2><p>ניהול המשפחה במקום אחד</p><section className="cards"><article><b>7</b><span>בני משפחה</span></article><article><b>{db.length}</b><span>תנועות במאגר</span></article></section></>}{page==='members'&&<div className="members">{members.map(m=><article key={m}><h3>{m}</h3></article>)}</div>}{page==='transactions'&&<><div className="title"><div><h2>תנועות כספיות</h2><p>{filtered.length} תנועות</p></div><button onClick={()=>input.current?.click()}>📥 ייבוא</button></div>{filters}<section className="cards"><article><b>{money(income)}</b><span>הכנסות</span></article><article><b>{money(expenses)}</b><span>הוצאות</span></article><article><b>{money(income+refunds-expenses)}</b><span>מאזן</span></article></section><div className="tablewrap"><table><thead><tr><th>תאריך</th><th>תיאור</th><th>קטגוריה</th><th>סוג</th><th>מקור</th><th>סכום</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.transaction_date}</td><td>{r.description}</td><td>{r.category}</td><td>{r.expense_nature||r.transaction_type}</td><td>{r.source_type==='bank'?'בנק':'אשראי'}</td><td dir="ltr">{money(r.amount)}</td></tr>)}</tbody></table></div></>}{page==='summary'&&<><h2>סיכומים</h2>{filters}<section className="cards"><article><b>{money(income)}</b><span>הכנסות</span></article><article><b>{money(expenses)}</b><span>הוצאות</span></article><article><b>{money(refunds)}</b><span>החזרים וזיכויים</span></article><article><b>{money(income+refunds-expenses)}</b><span>מאזן</span></article></section><div className="tablewrap"><table><thead><tr><th>קטגוריה</th><th>סה״כ</th></tr></thead><tbody>{cats.map(([c,v]:any)=><tr key={c}><td>{c}</td><td>{money(v)}</td></tr>)}</tbody></table></div></>}</main><input ref={input} hidden type="file" accept=".xls,.xlsx" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/>{preview.length>0&&<div className="modal"><div className="dialog"><h2>אישור ייבוא — {fileName}</h2><p>{preview.length} תנועות נמצאו</p><div className="tablewrap"><table><tbody>{preview.slice(0,100).map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.description}</td><td>{r.category}</td><td>{money(r.amount)}</td></tr>)}</tbody></table></div><div className="actions"><button disabled={saving} onClick={save}>{saving?'שומר...':'אישור ושמירה'}</button><button onClick={()=>setPreview([])}>ביטול</button></div></div></div>}{msg&&<div className="authMessage">{msg}</div>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);